language: csharp
solution: SampleEngine.sln

matrix:
  include:
    - dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1
    - mono: latest
    
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore SampleEngine.sln